server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /runtime-config.js {
        add_header Cache-Control "no-store";
        alias /tmp/runtime-config.js;
        default_type application/javascript;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
